//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ph.d_Application_Form.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdditionalPhDDetail
    {
        public int AdditionalID { get; set; }
        public Nullable<int> ApplicantID { get; set; }
        public Nullable<int> UniversityID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public string ExamType { get; set; }
        public string Score { get; set; }
        public Nullable<int> ExamYear { get; set; }
        public string InstituteName { get; set; }
        public string InstituteCity { get; set; }
        public string InstituteState { get; set; }
        public string InstituteAddress { get; set; }
        public string InstitutePincode { get; set; }
        public Nullable<bool> IsEmployed { get; set; }
        public string EmployerName { get; set; }
        public string CurrentDesignation { get; set; }
        public string EmployerAddress { get; set; }
        public Nullable<System.DateTime> DateOfJoining { get; set; }
        public string Experience { get; set; }
        public Nullable<System.DateTime> DateOfEnrollmentAsAdvocate { get; set; }
        public string ReasonForPursuing { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
    
        public virtual School School { get; set; }
        public virtual University University { get; set; }
        public virtual Applicant Applicant { get; set; }
    }
}
