//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ph.d_Application_Form.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int AdminID { get; set; }
        public string Name { get; set; }
        public string PhoneNumber { get; set; }
        public string EmailID { get; set; }
        public Nullable<int> UniversityID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Role { get; set; }
    }
}
