//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ph.d_Application_Form.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicantAcademicRecord
    {
        public int AcademicID { get; set; }
        public Nullable<int> ApplicantID { get; set; }
        public string EducationLevel { get; set; }
        public string InstituteName { get; set; }
        public string City { get; set; }
        public string GroupOrMajorSubjects { get; set; }
        public string MediumOfInstruction { get; set; }
        public string DurationYears { get; set; }
        public string ModeOfStudy { get; set; }
        public string MonthOfPassing { get; set; }
        public string YearOfPassing { get; set; }
        public string PercentageOrCGPA { get; set; }
    
        public virtual Applicant Applicant { get; set; }
    }
}
