//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ph.d_Application_Form.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applicant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Applicant()
        {
            this.AdditionalPhDDetails = new HashSet<AdditionalPhDDetail>();
            this.ApplicantBackgroundDetails = new HashSet<ApplicantBackgroundDetail>();
            this.ArticlesAndResearches = new HashSet<ArticlesAndResearch>();
            this.AwardsAndRecognitions = new HashSet<AwardsAndRecognition>();
            this.LanguageProficiencies = new HashSet<LanguageProficiency>();
            this.PhDEmploymentAndResearchDetails = new HashSet<PhDEmploymentAndResearchDetail>();
            this.Publications = new HashSet<Publication>();
            this.References = new HashSet<Reference>();
            this.SeminarOrConferences = new HashSet<SeminarOrConference>();
            this.WorkExperiences = new HashSet<WorkExperience>();
            this.ApplicantAcademicRecords = new HashSet<ApplicantAcademicRecord>();
            this.PhDQuestionnaires = new HashSet<PhDQuestionnaire>();
            this.ApplicationsReports = new HashSet<ApplicationsReport>();
            this.Users = new HashSet<User>();
        }
    
        public int ApplicantID { get; set; }
        public Nullable<int> UniversityID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<int> CourseID { get; set; }
        public string ProgramMode { get; set; }
        public string Prefix { get; set; }
        public string FullName { get; set; }
        public string FatherMotherName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Gender { get; set; }
        public string BloodGroup { get; set; }
        public string Category { get; set; }
        public string AadhaarNumber { get; set; }
        public string Email { get; set; }
        public string ParentEmail { get; set; }
        public string MobileNumber { get; set; }
        public string AlternateContact { get; set; }
        public string WhatsAppNumber { get; set; }
        public string AddressLine { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Pincode { get; set; }
        public string PhotoPath { get; set; }
        public string SignaturePath { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
        public string ApplicationNo { get; set; }
        public string TransactionNo { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string TransactionCategory { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdditionalPhDDetail> AdditionalPhDDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicantBackgroundDetail> ApplicantBackgroundDetails { get; set; }
        public virtual PhDCours PhDCours { get; set; }
        public virtual School School { get; set; }
        public virtual University University { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArticlesAndResearch> ArticlesAndResearches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AwardsAndRecognition> AwardsAndRecognitions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LanguageProficiency> LanguageProficiencies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhDEmploymentAndResearchDetail> PhDEmploymentAndResearchDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Publication> Publications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reference> References { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeminarOrConference> SeminarOrConferences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkExperience> WorkExperiences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicantAcademicRecord> ApplicantAcademicRecords { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhDQuestionnaire> PhDQuestionnaires { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicationsReport> ApplicationsReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
    }
}
