//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ph.d_Application_Form.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationsReport
    {
        public int ApplicantReportID { get; set; }
        public int ApplicantID { get; set; }
        public string ApplicationNumber { get; set; }
        public Nullable<bool> PersonalDetails { get; set; }
        public Nullable<System.DateTime> PersonalDetailsDate { get; set; }
        public Nullable<bool> AcademicDetails { get; set; }
        public Nullable<System.DateTime> AcademicDetailsDate { get; set; }
        public Nullable<bool> LastAttended { get; set; }
        public Nullable<System.DateTime> LastAttendedDate { get; set; }
        public Nullable<bool> WorkExperienceAwards { get; set; }
        public Nullable<System.DateTime> WorkExperienceAwardsDate { get; set; }
        public Nullable<bool> ArticlesReferences { get; set; }
        public Nullable<System.DateTime> ArticlesReferencesDate { get; set; }
        public Nullable<bool> PublicationsExperiencesReferences { get; set; }
        public Nullable<System.DateTime> PublicationsExperiencesReferencesDate { get; set; }
        public Nullable<bool> EmploymentResearch { get; set; }
        public Nullable<System.DateTime> EmploymentResearchDate { get; set; }
        public Nullable<bool> Questionnaire { get; set; }
        public Nullable<System.DateTime> QuestionnaireDate { get; set; }
        public Nullable<bool> FinalSubmission { get; set; }
        public Nullable<System.DateTime> FinalSubmissionDate { get; set; }
        public System.DateTime InsertedDate { get; set; }
        public Nullable<int> UniversityID { get; set; }
        public Nullable<int> SchoolID { get; set; }
    
        public virtual Applicant Applicant { get; set; }
    }
}
