//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ph.d_Application_Form.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicantBackgroundDetail
    {
        public int BackgroundID { get; set; }
        public int ApplicantID { get; set; }
        public int UniversityID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public string DomicileStatus { get; set; }
        public string SourceOfContact { get; set; }
        public string MotherName { get; set; }
        public string MotherQualification { get; set; }
        public Nullable<decimal> MotherAnnualIncome { get; set; }
        public string MotherContactNumber { get; set; }
        public string FatherName { get; set; }
        public string FatherQualification { get; set; }
        public Nullable<decimal> FatherAnnualIncome { get; set; }
        public string FatherContactNumber { get; set; }
        public string ImageCode { get; set; }
    
        public virtual School School { get; set; }
        public virtual University University { get; set; }
        public virtual Applicant Applicant { get; set; }
    }
}
