//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ph.d_Application_Form.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticlesAndResearch
    {
        public int ArticleID { get; set; }
        public int ApplicantID { get; set; }
        public int UniversityID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public string TitleOfArticle { get; set; }
        public string JournalOrMagazine { get; set; }
        public Nullable<System.DateTime> PublishedDate { get; set; }
    
        public virtual School School { get; set; }
        public virtual University University { get; set; }
        public virtual Applicant Applicant { get; set; }
    }
}
