//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ph.d_Application_Form.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PHDEntities : DbContext
    {
        public PHDEntities()
            : base("name=PHDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PhDCours> PhDCourses { get; set; }
        public virtual DbSet<School> Schools { get; set; }
        public virtual DbSet<University> Universities { get; set; }
        public virtual DbSet<AdditionalPhDDetail> AdditionalPhDDetails { get; set; }
        public virtual DbSet<ApplicantBackgroundDetail> ApplicantBackgroundDetails { get; set; }
        public virtual DbSet<ArticlesAndResearch> ArticlesAndResearches { get; set; }
        public virtual DbSet<AwardsAndRecognition> AwardsAndRecognitions { get; set; }
        public virtual DbSet<LanguageProficiency> LanguageProficiencies { get; set; }
        public virtual DbSet<PhDEmploymentAndResearchDetail> PhDEmploymentAndResearchDetails { get; set; }
        public virtual DbSet<Reference> References { get; set; }
        public virtual DbSet<SeminarOrConference> SeminarOrConferences { get; set; }
        public virtual DbSet<WorkExperience> WorkExperiences { get; set; }
        public virtual DbSet<Publication> Publications { get; set; }
        public virtual DbSet<Applicant> Applicants { get; set; }
        public virtual DbSet<ApplicantAcademicRecord> ApplicantAcademicRecords { get; set; }
        public virtual DbSet<PhDQuestionnaire> PhDQuestionnaires { get; set; }
        public virtual DbSet<PaymentReport> PaymentReports { get; set; }
        public virtual DbSet<ApplicationsReport> ApplicationsReports { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
    }
}
