//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ph.d_Application_Form.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentReport
    {
        public int PaymentReportID { get; set; }
        public string ApplicationNo { get; set; }
        public string TransactionNo { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public string TransactionCategory { get; set; }
        public System.DateTime RegisteredDate { get; set; }
        public string Program { get; set; }
        public string ProgramType { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<int> UniversityID { get; set; }
        public Nullable<int> ApplicantID { get; set; }
    }
}
