//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ph.d_Application_Form.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhDCours
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhDCours()
        {
            this.Applicants = new HashSet<Applicant>();
        }
    
        public int CourseID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<int> UniversityID { get; set; }
        public string CourseName { get; set; }
        public bool AllowsFullTime { get; set; }
        public bool AllowsPartTime { get; set; }
    
        public virtual School School { get; set; }
        public virtual University University { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Applicant> Applicants { get; set; }
    }
}
