//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ph.d_Application_Form.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhDEmploymentAndResearchDetail
    {
        public int EmploymentResearchID { get; set; }
        public int ApplicantID { get; set; }
        public int UniversityID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public bool IsEmployed { get; set; }
        public string PresentEmployerName { get; set; }
        public string EmployeeDesignation { get; set; }
        public Nullable<bool> HasAttachedNOC { get; set; }
        public Nullable<bool> HasEmployerPermission { get; set; }
        public string ResearchArea { get; set; }
        public string ResearchProblemStatement { get; set; }
    
        public virtual School School { get; set; }
        public virtual University University { get; set; }
        public virtual Applicant Applicant { get; set; }
    }
}
