//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ph.d_Application_Form.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhDQuestionnaire
    {
        public int QuestionnaireID { get; set; }
        public int ApplicantID { get; set; }
        public int UniversityID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<bool> AssociatedWithICFAI { get; set; }
        public string ProposedResearchTopic { get; set; }
        public string ReasonForJoining { get; set; }
        public Nullable<bool> KnowAnyoneInICFAI { get; set; }
        public string IntendedResearchArea { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
    
        public virtual Applicant Applicant { get; set; }
        public virtual School School { get; set; }
        public virtual University University { get; set; }
    }
}
