//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ph.d_Application_Form.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publication
    {
        public int PublicationID { get; set; }
        public Nullable<int> ApplicantID { get; set; }
        public Nullable<int> UniversityID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public string TitleOfPaper { get; set; }
        public string Authors { get; set; }
        public string Journal { get; set; }
        public string IndexedIn { get; set; }
        public string VolumeNo { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> PageFromTo { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
    
        public virtual School School { get; set; }
        public virtual University University { get; set; }
        public virtual Applicant Applicant { get; set; }
    }
}
