//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ph.d_Application_Form.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserID { get; set; }
        public int ApplicantID { get; set; }
        public string EmailID { get; set; }
        public string PasswordHash { get; set; }
        public int UniversityID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public string VisibleSteps { get; set; }
        public Nullable<int> CurrentStep { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
        public string status { get; set; }
        public string Role { get; set; }
        public Nullable<int> AdminID { get; set; }
    
        public virtual Applicant Applicant { get; set; }
    }
}
